# Generated by Django 5.1.6 on 2025-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_image', models.URLField()),
                ('agency_specialist', models.CharField(max_length=50)),
                ('agency_fullname', models.CharField(max_length=60)),
                ('agency_text', models.CharField(max_length=150)),
                ('agency_about_title', models.CharField(max_length=100)),
                ('agency_about_heading', models.CharField(max_length=200)),
                ('agency_buisbusines', models.CharField(max_length=200)),
                ('agency_dec', models.TextField()),
                ('business_dolor', models.CharField(max_length=100)),
                ('about_us', models.CharField(max_length=100)),
                ('about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.URLField()),
                ('project_title', models.CharField(max_length=100)),
                ('project_heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisnes_consulting', models.CharField(max_length=255)),
                ('buisnes_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModelEmployes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_image', models.URLField()),
                ('services_title', models.CharField(max_length=120)),
                ('consulting_points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_slider', models.URLField()),
                ('project', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
